#!/bin/bash

history-choser() {
    history_grep_search_type=$1
    history_filter_string=$2
    export hgg_file=$(mktemp)
    export hgg_chosen=$(mktemp)

    if [[ $history_grep_search_type == "recent" ]]; then
        hggr $history_filter_string > $hgg_file
    else
        hgg $history_filter_string > $hgg_file
    fi

    node ~/git/bgrc/node-choser/index.js
    command=$(cat $hgg_chosen|awk '{$1=""; $2=""; sub("  ", ""); print}')
    eval "$command"

    # Manually add to history
    echo -e "#$(date +%s)\n${command}" >> ${history_session_dir}/${history_session_file}
    history -r ${history_session_dir}/${history_session_file}

    rm $hgg_file $hgg_chosen
}

alias hggc='history-choser all'
alias hggrc='history-choser recent'
alias hh='history-choser recent'

